### ISSUE TITLE
[Windows] System cannot find path speficied

### ISSUE THREAD

**Issue by sskhokhar** [mean-expert-official/fireloop.io#21]
There is an error while creating Angular2 Web using fireloop command

Creating new Angular 2 Application: webapp
The system cannot find the path specified.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@mean-exp
ert\fireloop\node_modules\angular-cli\lib\cli\index.js.bin/ng  ENOENT
    at notFoundError (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\
@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@
mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_m
odules\@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

At first fireloop command works fine and yields the loopback backend successfully but gives error while generating angular 2 webapp

**Comment by jonathan-casarrubias** [comment]
Hi @sskhokhar, thanks for reaching out!!!

Hey so, yes I think I know the issue I will update the path resolver for windows based filesystem

Thanks for reporting

**Comment by jonathan-casarrubias** [comment]
@sskhokhar I just published a new version, I updated the regex for the angular cli path resolver. Though I'm unable to test in a windows machine the regex was tested using backslashes.

Would you mind to update to alpha 23 and see if works now?

Thanks
jon

**Comment by sskhokhar** [comment]
@jonathan-casarrubias I updated to alpha 23 but error still persists

Creating new Angular 2 Application: webapp
'"C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@mean-expert\fireloo
p\node_modules.bin/ng "' is not recognized as an internal or external command,
operable program or batch file.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@mean-exp
ert\fireloop\node_modules.bin/ng  ENOENT
    at notFoundError (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\
@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@
mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_m
odules\@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by jonathan-casarrubias** [comment]
Ok I just published another approach in alpha 24, I believe this will be the right one... I'm using path now to resolve the file system directory.

**Comment by sskhokhar** [comment]
Yet another error. It generates the angular 2 app but gives error while generating SDK.

```
 _-----_
|       |    ?──────────────────────────?
|--(o)--|    │  Building your FireLoop  │
```

   `---------'   │           SDK!           │
    ( _'U`_ )    ?──────────────────────────?
    /**_A**_\   /
     |  ~  |
   **'._**.'__
 '   `|° ' Y`

Generating: webapp/src/app/app.module.ts
Generating: webapp/src/tsconfig.json
Generating: webapp/src/typings.d.ts
The system cannot find the path specified.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@mean-exp
ert\fireloop\node_modules\ts-node\dist\index.js.bin/ts-node ENOENT
    at notFoundError (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\
@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_modules\@
mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_m
odules\@mean-expert\fireloop\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

C:\Users\Shahrukh Shahid\Desktop\fireloop>npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "prefix" "-g"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPIPE
npm ERR! errno EPIPE
npm ERR! syscall write

npm ERR! write EPIPE
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Shahrukh Shahid\Desktop\fireloop\webapp\npm-debug.log

**Comment by jonathan-casarrubias** [comment]
I see, same error but in another generator.

So, the one that generates the angular 2 has been fixed then. But now I will go through the rest of the generators and search for paths.

This error seems to be now within the SDK generator and now I can assume the one that serves the application will have the same issue.

I appreaciate your patience.
Cheers
Jon

**Comment by jonathan-casarrubias** [comment]
I just went through all of the generators and updated any directory reference to use normalized paths.

It still is working in Mac, its unfortunate I don't have a win machine around available but I believe that if the ng2 generator already worked, the rest should now work.

**Comment by sskhokhar** [comment]
Error!

```
 _-----_
|       |    ?──────────────────────────?
|--(o)--|    │  Building your FireLoop  │
```

   `---------'   │           SDK!           │
    ( _'U`_ )    ?──────────────────────────?
    /**_A**_\   /
     |  ~  |
   **'._**.'__
 '   `|° ' Y`

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at Object.<anonymous> (C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_mod
ules\@mean-expert\fireloop\node_modules\ts-node\src_bin.ts:182:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by jonathan-casarrubias** [comment]
well, is not complaining about a directory anymore.. But this new error is anything but specific. It says  ) is missing but I dont see where... Ill need to get a win machine to debug this. 

Also Ill try to install a VM, I will need to get a copy of win then lol.

sight..

**Comment by sskhokhar** [comment]
I tried to debug the issue but infact I couldnt find the file as mentioned

C:\Users\Shahrukh Shahid\AppData\Roaming\npm\node_mod
ules\@mean-expert\fireloop\node_modules\ts-node\src_bin.ts

**Comment by jonathan-casarrubias** [comment]
Yes the issue seems to be thrown from ts-node.

The good news is that I was able to get a win10 lap, so I will setup and test before publishing

Thanks for looking at the issue.

Regards
Jon

**Comment by jonathan-casarrubias** [comment]
Hey @sskhokhar good news, having access to a win machine I found there were several issues ahead.

The great news is that I already fixed most of them, there are no bad news... just the time I need to finish and publish.

Cheers
Jon

**Comment by sskhokhar** [comment]
Hi @jonathan-casarrubias glad to know that you have fixed errors. Now you must use virtual machine with windows for further development.
I want to ask you something, would you please bother to share your email address?

Regards,

**Comment by jonathan-casarrubias** [comment]
sure my email is public in the home of this repo: https://github.com/mean-expert-official

but shortcut: jcasarrubias@mean.expert

**Comment by jonathan-casarrubias** [comment]
Hey @sskhokhar after several hours I fixed and tested the fireloop cli working in windows. At least at the same level as in mac or linux.

Of course this is still alpha version and there are features not yet implemented. Though it is enough to build a complex real-time web application.

I saw your email, I'll take the time to answer in the morning..

Cheers
Jon

**Comment by luncht1me** [comment]
I'm getting these issues now.

```
npm ERR! addLocal Could not install C:\Users\lunchtime\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\generator-fireloop
npm ERR! addLocal Could not install C:\Users\lunchtime\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\generator-loopback
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "E:\\nodejs\\node.exe" "E:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop" "@angular/cli" "@mean-expert/fireloop"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! path C:\Users\lunchtime\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\generator-fireloop
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\lunchtime\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\generator-fireloop'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\lunchtime\AppData\Roaming\npm\node_modules\@mean-expert\fireloop\generator-fireloop'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Gitlab\highnoonin\npm-debug.log
```

This seems to be a problem with beta2.
I'm currently installing beta 1.3, seems to be moving along.

**Comment by jonathan-casarrubias** [comment]
@luncht1me Fixed on beta 2.3
